linters-settings:
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - bodyclose
    - staticcheck
    - revive
    - govet
    - unconvert
    - unused
    - gosec
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc

  fast: false

run:
  concurrency: 4

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "package-comments: should have a package comment"
      linters:
        - revive
  exclude-use-default: false
