version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - staticcheck
    - revive
    - govet
    - unconvert
    - unused
    - gosec
    - misspell
    - unparam
    - ineffassign
    - gochecknoinits
    # - copyloopvar  # Disabled as it conflicts with code supporting Go <1.22
    - gocritic
    - nakedret
    - prealloc
  
  settings:
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
  
  exclusions:
    paths:
      - vendor
    rules:
      - text: "weak cryptographic primitive"
        linters:
          - gosec
      - text: "package-comments: should have a package comment"
        linters:
          - revive
      - path: _test\.go
        linters:
          - revive
        text: "unused-parameter"

run:
  concurrency: 4
