// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/feed-master/app/youtube/channel"
)

// ChannelServiceMock is a mock implementation of youtube.ChannelService.
//
// 	func TestSomethingThatUsesChannelService(t *testing.T) {
//
// 		// make and configure a mocked youtube.ChannelService
// 		mockedChannelService := &ChannelServiceMock{
// 			GetFunc: func(ctx context.Context, chanID string) ([]channel.Entry, error) {
// 				panic("mock out the Get method")
// 			},
// 		}
//
// 		// use mockedChannelService in code that requires youtube.ChannelService
// 		// and then make assertions.
//
// 	}
type ChannelServiceMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, chanID string) ([]channel.Entry, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChanID is the chanID argument value.
			ChanID string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *ChannelServiceMock) Get(ctx context.Context, chanID string) ([]channel.Entry, error) {
	if mock.GetFunc == nil {
		panic("ChannelServiceMock.GetFunc: method is nil but ChannelService.Get was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChanID string
	}{
		Ctx:    ctx,
		ChanID: chanID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, chanID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedChannelService.GetCalls())
func (mock *ChannelServiceMock) GetCalls() []struct {
	Ctx    context.Context
	ChanID string
} {
	var calls []struct {
		Ctx    context.Context
		ChanID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
